### ISSUE TITLE
Needs to be able to handle multiple discourse instances in config

### ISSUE THREAD

**Issue by pacharanero** [oblakeerickson/discourse_cli#1]
This tool is fantastic and great to see. I run several Discourse instances and to be able to interact with them through a CLI is great.

Because I run several instances it would be great to have the facility to configure multiple instances in your ~/.discourse_cli config file:

```
instance-one:
  host: some.ip.address.here
  api_key: 2e07ed2f1570c9dee581a4f4442d0a3f17ce951c6eb2807389217ced82422272
  api_username: discourse-one

instance-two:
  host: someother.ip.address.here
  api_key: 3f17ce951c6eb2807389217ced824222722e07ed2f1570c9dee581a4f4442d0a
  api_username: discourse-two
```

so the command line invocation would be: `$ discourse instance-one categories` for example.

Marcus
